### ISSUE TITLE
Syntax highlighting not working as shown in the README

### ISSUE THREAD

**Issue by programming-passion** [andytruett/vscode-textFSM-syntax#4]
I installed this VS Code extension, and noticed that the syntax highlighting is not working as shown in the sample screenshot. 

![image](https://user-images.githubusercontent.com/845885/67626155-63919e00-f815-11e9-825f-ac339f5c485c.png)

Image in the README:
![image](https://user-images.githubusercontent.com/845885/67626160-71472380-f815-11e9-87ca-47f5e1eacd8c.png)

Let me know if I am missing something obvious

**Comment by andytruett** [comment]
My first thought is that you may be using a color theme (looks like the default one in your screenshot) that doesn't differentiate between the syntax contexts that are in in this extension.

Try another theme? [This one](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme) works on my test installs.

**Comment by programming-passion** [comment]
Thank you, Andy. I'll give this a try

**Comment by andytruett** [comment]
@programming-passion Any luck?

**Comment by programming-passion** [comment]
Hello Andy,
Thank you for following up.
I am still seeing the same issue with the theme you recommended

**Comment by andytruett** [comment]
So we're on the same page, some things to double-check:

You installed the linked theme and [activated it as your theme](https://code.visualstudio.com/docs/getstarted/themes#_selecting-the-color-theme) (verifiable via settings, search for _theme_)

Your file is one of these extensions: ".template", ".textfsm", ".fsm" **or** you've manually set the file syntax ([Language mode](https://code.visualstudio.com/docs/languages/overview#_language-features-in-vs-code))

If these are both accurate statements, would you use the command "Inspect TM Scopes" and click something you expect to be colored? I'd like to see whether this extension is correctly assigning syntax.

**Comment by programming-passion** [comment]
Hello Andy,

It looks like I didnt activate the theme properly before. After I activated the theme by following the instructions you had shared, I am able to see the colors highlighted properly. Thanks again for all your help!

**Comment by andytruett** [comment]
Glad to be of assistance!
