### ISSUE TITLE
Color Syntax not working

### ISSUE THREAD

**Issue by pabloveliz** [andytruett/vscode-textFSM-syntax#5]
Using version 1.0.4, and when running command "_Developer: Inspect Editor Tokens and Scopes_" says
**No grammar provided for <text.textFSM>**

I'm using Visual Studio Code version 1.44.2 on Linux 5.3.0

**Comment by andytruett** [comment]
Merged your pull request and pushed to VSCode marketplace - fixed for you?

**Comment by pabloveliz** [comment]
Yes, indeed, it's fixed!. Thanks
